server:
  port: 8083
spring:
  application:
    name: SpringBootTest
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: '*'
    schema:
      printer:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/GraphQL?useSSL=false
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update